apiVersion: k8s.refunc.io/v1beta3
kind: Xenv
metadata:
  name: provided
spec:
  type: lambda
  transport: nats
  poolSize: 1
  container:
    image: lambci/lambda:provided
    imagePullPolicy: IfNotPresent
